[package]
name = "hyper_lua_actor"
version = "0.1.1"
license = "MIT"
authors = ["JunYi JohnTeee Lee <johnteee@gmail.com>"]
include = ["src/**/*.rs", "Cargo.toml"]
readme = "README.md"
description = "Binding of lua_actor & hyper"
documentation = "https://docs.rs/hyper_lua_actor/"
homepage = "https://github.com/TeaEntityLab/hyperLuaActor"
repository = "https://github.com/TeaEntityLab/hyperLuaActor"
keywords = ["lua","actor","binding","async", "hyper"]

[badges.maintenance]
status = "actively-developed"

[lib]
name = "hyper_lua_actor"
path = "src/lib.rs"

[features]
default = [
    "runtime",
]
runtime = [
    "tokio",
]

[dependencies]
fp_rust="0.*"
rlua="0.*"
lua_actor="0.*"

hyper="0.*"
futures="0.1.*"
url="1.*"
tokio = { version = "0.1.7", optional = true }

[[test]]
name = "bind"
path = "tests/bind.rs"
required-features = ["runtime"]
